### ISSUE TITLE
problem in calling function

### ISSUE THREAD

**Issue by harshaddas** [Pay-Dirt/k12mwa#4]
<a href="" ng-click="removeTeacher({{id}})">Remove</a></li>

$scope.removeTeacher = function(id)
	{ console.log("hi");
console.log(id);
	};

remove teacher ke ander id jaa rahi h lekin hume lag raha h function removeTeacher call nhi ho raha h kyo console me kuch print nhi ho raha

**Comment by akashvyom** [comment]
I can't tell anything by this much info please upload concerned files
